# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
 System.Debug: true

stages:

- stage: Build_Artifacts
  
  jobs:
  - job: Random
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'
    - script: |
       echo Add other tasks to build, test, and deploy your project.
       echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'
  - job: Generate_Artifacts
    dependsOn: Random
    steps:
    - task: PowerShell@2
      inputs:
       filePath: '$(System.DefaultWorkingDirectory)\Euryale\New-TestFile.ps1'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)\text.txt'
        ArtifactName: 'buildArtifacts'
        publishLocation: 'Container'


- stage: Deploy_Dev
  variables: 
   - template: development_vars.yml
  jobs:
  - deployment: DevelopmentDeployment
    environment: Dev
    strategy:
      runOnce:
        deploy:
          steps:
          - template: 'deploy.yml'
            parameters: {type: 'primary_Dev', spn: 'SPN_Dev', variablesTemplate: 'dev_vars.yml'}


- stage: Deploy_QE
  variables: 
  - template: qe_vars.yml
  jobs:
  - deployment: QEDeployment
    environment: QE
    strategy:
      runOnce:
        deploy:
          steps: 
          - template: 'deploy.yml'
            parameters: {type: 'primary_QE', spn: 'SPN_QE', variablesTemplate: 'qe_vars.yml'}
