# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
 System.Debug: true

stages:

- stage: Build_Artifacts
  
  jobs:
  - job: Random
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'
    - script: |
       echo Add other tasks to build, test, and deploy your project.
       echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'
  - job: Generate_Artifacts
    steps:
    - task: PowerShell@2
      inputs:
       filePath: '$(System.DefaultWorkingDirectory)\Euryale\New-TestFile.ps1'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)\text.txt'
        ArtifactName: 'drop'
        publishLocation: 'Container'



- stage: Deploy_Dev
  variables: 
   STAGE_VAR: 'Dev'
  jobs:
  - deployment: DevelopmentDeployment
    environment: Dev
  - job:
    steps:

    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'

    - task: replacetokens@3
      inputs:
        rootDirectory: '$(System.ArtifactsDirectory)'
        targetFiles: '**/*.txt'
        encoding: 'auto'
        writeBOM: true
        actionOnMissing: 'warn'
        keepToken: false
        tokenPrefix: '#{'
        tokenSuffix: '}#'
        useLegacyPattern: false
        enableTelemetry: true

- stage: Devploy_QE
  variables: 
   STAGE_VAR: 'QE'
  jobs:
  - deployment: DevelopmentDeployment
    environment: QE