# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

stages:

- stage: Build_Artifacts
  
  jobs:
  - job: Random
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'
    - script: |
       echo Add other tasks to build, test, and deploy your project.
       echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'
  - job: Generate_Artifacts
    steps:
    - task: PowerShell@2
      inputs:
       filePath: '$(System.DefaultWorkingDirectory)\Euryale\New-TestFile.ps1'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)\Euryale\text.txt'
        ArtifactName: 'drop'
        publishLocation: 'Container'



- stage: Deploy_Dev
  jobs:
  - deployment: DevelopmentDeployment
    environment: Dev

- stage: Devploy_QE
  jobs:
  - deployment: DevelopmentDeployment
    environment: QE